config/routes.rb
Rails.application.routes.draw do
  root 'questions#newest'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'register' => 'users#new'
  resources :users, only: [:create, :show, :destroy]

  resources :questions, shallow: true do
    resources :answers, except: [:show, :index]
    resources :comments, except: [:index, :show]
  end
  get 'newest' => 'questions#newest', as: 'questions/newest'
  get 'trending' => 'questions#trending', as: 'questions/trending'
  get 'highest_voted' => 'questions#highest_voted', as: 'questions/highest_voted'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  validates :content, length: { minimum: 10 }
  validates_presence_of :content, :title, :author
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  skip_before_action :ensure_logged_in, only: :show

  def index
    @qs = Question.all
  end

  def new
    @qs = Question.new
  end

  def create
    @qs = current_user.questions.build(qs_params)
    if @qs.save
      redirect_to questions_path
    else
      render 'new'
    end    
  end

  private
  def qs_params
    params.require(:question).permit(:title, :content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :ensure_logged_in, only: [:index, :show]

  def index
    @questions = Question.all
  end

  def newest
    @questions = Question.all
    @most_recent = Question.order(created_at: :desc)
  end

  def trending
    @questions = Question.all
    @trending = Question.order(updated_at: :desc).limit(10)
  end

  def highest_voted
    @questions = Question.all
      @highest_voted = Vote.
      where(votable_type: 'Question').
      order('sum_value DESC').
      group(:votable_id).
      limit(10).
      sum(:value)
    @highest_voted = @highest_voted.map { |x| Question.find(x[0]) }

    # @highest_voted = Question.joins(
    #   # Question.joins = SELECT questions.* FROM questions
    #   'JOIN (SELECT votable_id, SUM(value) AS score
    #   FROM votes WHERE votable_type = \'Question\'
    #   GROUP BY votable_id
    #   ORDER BY score DESC) v ON questions.id = v.votable_id'
    #   # Sub-join table with alias of v -- where v contains votable_id and sum of vote values (temp in memory) -- on questions.id and votable_id.
    # )
  end

  def new
    @qs = Question.new
  end

  def create
    if logged_in?
      @qs = current_user.questions.build(qs_params)
      if @qs.save
        redirect_to questions_path
      else
        render 'new'
      end
    else
      @qs = Question.new
      @qs.errors.add(:user, "must be logged in")
      render 'new'
    end
  end

  def show
    @qs = find_qs
    @comments = @qs.comments
    @answers = @qs.answers
  end

  def edit
    @qs = find_qs
  end

  def update
    @qs = find_qs
    if @qs.update(qs_params)
      redirect_to @qs
    else
      render 'edit'
    end
  end

  def destroy
    @qs = find_qs
    @qs.destroy
    redirect_to questions_path
  end


  private
  def qs_params
    params.require(:question).permit(:title, :content)
  end

  def find_qs
    Question.find(params[:id])
  end
end

app/views/questions/_ad.html.erb
<%= image_tag "ruby-ad.png" %>

app/views/questions/_form.html.erb
<ul class="no-list-style no-padding">
  <%= form_for @qs do |f| %>
    <li><%= f.label :title,  class: "form-field" %></li>
    <li><%= f.text_field :title, placeholder: "What's your programming question? Be specific.", class: "form-field" %></li>
    <li><%= f.label :content,  class: "form-field" %></li>
    <li><%= f.text_area :content,  class: "form-field content-field" %></li>
    <li><%= submit_tag("Post Your Question", class: "form-button") %></li>
  <% end %>
</ul>

app/views/questions/_meta.html.erb
<div class="col-md-1 text-center no-padding">
  <p class="vote-count"><%= element.votes.count %></p>
  <p class="vote-count-sub-header">votes</p>
  <div class="answer-count-container">
    <p class="answer-meta answer-count"><%= element.answers.count %></p>
    <p class="answer-meta answer-count-sub-header">answers</p>
  </div>
</div>

app/views/questions/_post_preview.html.erb
<div class="row post-preview ">

  <%= render partial: 'meta', locals: {element: element} %>

  <div class="col-md-11">
    <li class="post-preview-title"><%= link_to element.title, question_path(element) %></li>
    <li><%= markdown(element.content[0..200]) %></li>
  </div>

</div>

app/views/questions/_questions_count.html.erb
<div class="col-md-3">
  <span class="total-num-questions"><%= @questions.count %></span>
  <p>questions</p>
</div>

app/views/questions/edit.html.erb
<div class="row static-width main-content-container">

  <div class="col-md-7 col-md-offset-1">
    <h1>Edit Question Details</h1>
    <%= render partial: 'layouts/errors', locals: { element: @qs } %>
    <%= render 'form' %>
  </div>

  <div class="col-md-3">
    <div class="col-md-12 question-meta">
      <h1 class="question-meta-header">How to Ask</h1>
      <strong>Is your question about programming?</strong>
      <p>We prefer questions that can be answered, not just discussed.</p>
      <p>Provide details. Share your research.</p>
      <p>If your question is about this website, <span class="primary-blue">ask it on meta</span> instead.</p>
    </div>

    <div class="col-md-12 question-meta">
      <h1 class="question-meta-header">How to Format</h1>
      <h2 class="question-meta-sub-header">Our form fields now support Markdown!</h2>
      <ul class="question-meta-markdown-tips">
        <li>_italic_ or **bold**</li>
        <li>put returns between paragraphs</li>
        <li>use ``` followed by language to enter code blocks</li>
        <li>quote by place > at the start of line</li>
        <li>to add links use:</li>
        <li>[alt text](http://foo.com)</li>
        <li><span class="primary-blue">basic HTML</span> also allowed</li>
        <li><a href="https://daringfireball.net/projects/markdown/"><span class="primary-blue">formating help</span></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/questions/frequent.html.erb
<div class="row static-width main-content-container">

  <div class="col-md-7 col-md-offset-1">

    <%= render 'questions/nav/frequent_nav' %>

    <ul class="no-list-style">

      <% @trending.each do |qs| %>

        <%= render partial: 'post_preview', locals: {element: qs} %>

      <% end %>

    </ul>

  </div>

  <div class="col-md-3 text-center">
    <%= render 'questions_count' %>
    <%= render 'ad' %>
  </div>

</div>

app/views/questions/highest_voted.html.erb
<div class="row static-width main-content-container">

  <div class="col-md-7 col-md-offset-1">

    <%= render 'questions/nav/votes_nav' %>

    <ul class="no-list-style">

      <% @highest_voted.each do |qs| %>

        <%= render partial: 'post_preview', locals: {element: qs} %>

      <% end %>

    </ul>

  </div>

  <div class="col-md-3 text-center">
    <%= render 'questions_count' %>
    <%= render 'ad' %>
  </div>

</div>

app/views/questions/index.html.erb
<div class="row static-width main-content-container">

  <div class="col-md-7 col-md-offset-1">

    <%= render 'questions/nav/all_nav' %>

    <ul class="no-list-style">

      <% @questions.each do |qs| %>

        <%= render partial: 'post_preview', locals: {element: qs} %>

      <% end %>

    </ul>

  </div>

  <div class="col-md-3 text-center">
    <%= render 'questions_count' %>
    <%= render 'ad' %>
  </div>

</div>

app/views/questions/new.html.erb
<div class="row static-width main-content-container">

  <div class="col-md-7 col-md-offset-1">
    <h1>Enter Question Details</h1>
    <%= render partial: 'layouts/errors', locals: { element: @qs } %>
    <%= render 'form' %>
  </div>

  <div class="col-md-3">
    <div class="col-md-12 question-meta">
      <h1 class="question-meta-header">How to Ask</h1>
      <strong>Is your question about programming?</strong>
      <p>We prefer questions that can be answered, not just discussed.</p>
      <p>Provide details. Share your research.</p>
      <p>If your question is about this website, <span class="primary-blue">ask it on meta</span> instead.</p>
    </div>

    <div class="col-md-12 question-meta">
      <h1 class="question-meta-header">How to Format</h1>
      <h2 class="question-meta-sub-header">Our form fields now support Markdown!</h2>
      <ul class="question-meta-markdown-tips">
        <li>_italic_ or **bold**</li>
        <li>put returns between paragraphs</li>
        <li>use ``` followed by language to enter code blocks</li>
        <li>quote by place > at the start of line</li>
        <li>to add links use:</li>
        <li>[alt text](http://foo.com)</li>
        <li><span class="primary-blue">basic HTML</span> also allowed</li>
        <li><a href="https://daringfireball.net/projects/markdown/"><span class="primary-blue">formating help</span></a></li>
      </ul>
    </div>
  </div>

</div>

app/views/questions/newest.html.erb
<div class="row static-width main-content-container">

  <div class="col-md-7 col-md-offset-1">

    <%= render 'questions/nav/newest_nav' %>

    <ul class="no-list-style">

      <% @most_recent.each do |qs| %>

        <%= render partial: 'post_preview', locals: {element: qs} %>

      <% end %>

    </ul>

  </div>

  <div class="col-md-3 text-center">
    <%= render 'questions_count' %>
    <%= render 'ad' %>
  </div>

</div>

app/views/questions/show.html.erb
<div class="row static-width main-content-container">
  <div class="col-md-10 col-md-offset-1">
    <h1><%= @qs.title %></h1>
    <hr>

    <div class="col-md-1">
      <%# link_to upvote button %>
      <%= @qs.votes.sum(:value) %>
      <%# link_to downvote button %>
    </div>

    <main class="col-md-8">
      <p><%= markdown(@qs.content) %></p>
      <!-- Prevent visitors from editing and deleting. -->
      <% if current_user == @qs.author %>
        <p>
          <%= link_to 'edit', edit_question_path %>
          <%= link_to 'delete', question_path(@qs), method: :delete, data: {confirm: 'Are you sure?'} %>
        </p>
      <% end %>

      <div class="col-md-offset-8">
        <p>
          asked <%= question_datetime(@qs.created_at) %>
        </p>
        <p>
          <img src="http://static.tumblr.com/9df6e4958d7e576121bad9f80db40364/p29zb6q/ROUnl7j85/tumblr_static_55ieoztgoxwkc0w4g4o0ck8o4.gif"/> <%= link_to @qs.author.username, user_path %>
        </p>
      </div>
      <hr>

      <% if logged_in? %>

        <div>
          <%= link_to 'Add Answer', new_question_answer_path(@qs.id) %>
        </div>
        <div>
          <%= link_to 'Add comment', new_question_comment_path(@qs.id) %>
        </div>

      <% end %>

      <div>
        <h3>Answers</h3>
        <% @answers.each do |answer| %>
          <%= markdown(answer.content) %>
          <div>
            by <%= answer.author.username %>
          </div>
          <div>
            <% if answer.author == current_user %>
              <%= link_to "edit", edit_answer_path(answer) %>
              <%= link_to "delete", answer_path(answer), method: :delete %>
            <% end %>
          </div>
        <% end %>
      </div>

      <div>
        <h3>Comments</h3>
        <% @comments.each do |comment| %>
          <%= markdown(comment.content) %>
          <div>
          by <%= comment.commentor.username %>
          </div>
          <div>
            <% if comment.commentor == current_user %>
              <%= link_to "edit", edit_comment_path(comment) %>
              <%= link_to "delete", comment_path(comment), method: :delete %>
            <% end %>
          </div>
        <% end %>
      </div>

    </main>

    <div class="col-md-3">
      <%= image_tag "ruby-ad.png" %>
    </div>
  </div>
</div>

app/views/questions/trending.html.erb
<div class="row static-width main-content-container">

  <div class="col-md-7 col-md-offset-1">

    <%= render 'questions/nav/trending_nav' %>

    <ul class="no-list-style">

      <% @trending.each do |qs| %>

        <%= render partial: 'post_preview', locals: {element: qs} %>

      <% end %>

    </ul>

  </div>

  <div class="col-md-3 text-center">
    <%= render 'questions_count' %>
    <%= render 'ad' %>
  </div>

</div>