config/routes.rb
Rails.application.routes.draw do
  root 'questions#newest'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'register' => 'users#new'
  resources :users, only: [:create, :show, :destroy]

  resources :questions, shallow: true do
    resources :answers, except: [:show, :index]
    resources :comments, except: [:index, :show]
  end
  get 'newest' => 'questions#newest', as: 'questions/newest'
  get 'trending' => 'questions#trending', as: 'questions/trending'
  get 'highest_voted' => 'questions#highest_voted', as: 'questions/highest_voted'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  validates :content, length: { minimum: 10 }
  validates_presence_of :content, :title, :author
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  skip_before_action :ensure_logged_in, only: :show

  def index
    @qs = Question.all
  end

  def new
    @qs = Question.new
  end

  def create
    @qs = current_user.questions.build(qs_params)
    if @qs.save
      redirect_to questions_path
    else
      render 'new'
    end    
  end

  private
  def qs_params
    params.require(:question).permit(:title, :content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :ensure_logged_in, only: [:index, :show]

  def index
    @questions = Question.all
  end

  def newest
    @questions = Question.all
    @most_recent = Question.order(created_at: :desc)
  end

  def trending
    @questions = Question.all
    @trending = Question.order(updated_at: :desc).limit(10)
  end

  def highest_voted
    @questions = Question.all
      @highest_voted = Vote.
      where(votable_type: 'Question').
      order('sum_value DESC').
      group(:votable_id).
      limit(10).
      sum(:value)
    @highest_voted = @highest_voted.map { |x| Question.find(x[0]) }

    # @highest_voted = Question.joins(
    #   # Question.joins = SELECT questions.* FROM questions
    #   'JOIN (SELECT votable_id, SUM(value) AS score
    #   FROM votes WHERE votable_type = \'Question\'
    #   GROUP BY votable_id
    #   ORDER BY score DESC) v ON questions.id = v.votable_id'
    #   # Sub-join table with alias of v -- where v contains votable_id and sum of vote values (temp in memory) -- on questions.id and votable_id.
    # )
  end

  def new
    @qs = Question.new
  end

  def create
    if logged_in?
      @qs = current_user.questions.build(qs_params)
      if @qs.save
        redirect_to questions_path
      else
        render 'new'
      end
    else
      @qs = Question.new
      @qs.errors.add(:user, "must be logged in")
      render 'new'
    end
  end

  def show
    @qs = find_qs
    @comments = @qs.comments
    @answers = @qs.answers
  end

  def edit
    @qs = find_qs
  end

  def update
    @qs = find_qs
    if @qs.update(qs_params)
      redirect_to @qs
    else
      render 'edit'
    end
  end

  def destroy
    @qs = find_qs
    @qs.destroy
    redirect_to questions_path
  end


  private
  def qs_params
    params.require(:question).permit(:title, :content)
  end

  def find_qs
    Question.find(params[:id])
  end
end

app/views/questions/nav/_all_nav.html.erb
<div class="row questions-nav-tab">
  <ul class="nav nav-tabs text-right">
    <li rol="presentation" class="active"><%= link_to "all", questions_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "newest", questions_newest_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "trending", questions_trending_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "votes", questions_highest_voted_path, class: "link" %></li>
  </ul>
</div>

app/views/questions/nav/_frequent_nav.html.erb
<div class="row questions-nav-tab">
  <ul class="nav nav-tabs">
    <li rol="presentation"><%= link_to "all", questions_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "newest", questions_newest_path, class: "link" %></li>
    <li rol="presentation" class="active"><%= link_to "frequent", questions_frequent_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "votes", questions_highest_voted_path, class: "link" %></li>
  </ul>
</div>

app/views/questions/nav/_newest_nav.html.erb
<div class="row questions-nav-tab">
  <ul class="nav nav-tabs">
    <li rol="presentation"><%= link_to "all", questions_path, class: "link" %></li>
    <li rol="presentation" class="active"><%= link_to "newest", questions_newest_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "trending", questions_trending_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "votes", questions_highest_voted_path, class: "link" %></li>
  </ul>
</div>

app/views/questions/nav/_trending_nav.html.erb
<div class="row questions-nav-tab">
  <ul class="nav nav-tabs">
    <li rol="presentation"><%= link_to "all", questions_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "newest", questions_newest_path, class: "link" %></li>
    <li rol="presentation" class="active"><%= link_to "trending", questions_trending_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "votes", questions_highest_voted_path, class: "link" %></li>
  </ul>
</div>

app/views/questions/nav/_votes_nav.html.erb
<div class="row questions-nav-tab">
  <ul class="nav nav-tabs">
    <li rol="presentation"><%= link_to "all", questions_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "newest", questions_newest_path, class: "link" %></li>
    <li rol="presentation"><%= link_to "trending", questions_trending_path, class: "link" %></li>
    <li rol="presentation" class="active"><%= link_to "votes", questions_highest_voted_path, class: "link" %></li>
  </ul>
</div>