config/routes.rb
Rails.application.routes.draw do
  root 'questions#newest'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'register' => 'users#new'
  resources :users, only: [:create, :show, :destroy]

  resources :questions, shallow: true do
    resources :answers, except: [:show, :index]
    resources :comments, except: [:index, :show]
  end
  get 'newest' => 'questions#newest', as: 'questions/newest'
  get 'trending' => 'questions#trending', as: 'questions/trending'
  get 'highest_voted' => 'questions#highest_voted', as: 'questions/highest_voted'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :questions, foreign_key: :author_id, dependent: :destroy
  has_many :answers, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :commentor_id, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :username, :password, :email, presence: true
  validates_uniqueness_of :username, :email
  validates :username, length: { minimum: 4 }
  validates :password, length: { minimum: 6 }
  validates :password, confirmation: true
  validates_presence_of :password_confirmation
  validates :email, :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    if request.xhr?
      render :new, layout: false
    else
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if request.xhr?
        session[:user_id] = @user.id
        render 'questions/newest', layout: false
      else
        session[:user_id] = @user.id
        redirect_to root_path
      end
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 text-left">
    <div class="register-form">
      <%= form_for :user, url: users_path do |f| %>
        <ul class="no-list-style">
          <li><%= f.label :username, class: "form-field" %></li>
          <li><%= f.text_field :username, class: "form-field" %></li>
          <li><%= f.label :email, class: "form-field" %></li>
          <li><%= f.text_field :email, class: "form-field" %></li>
          <li><%= f.label :password, class: "form-field" %></li>
          <li><%= f.password_field :password, class: "form-field" %></li>
          <li><%= f.label :confirm_password, class: "form-field" %></li>
          <li><%= f.password_field :password_confirmation, class: "form-field" %></li>
        </ul>

        <div class="col-md-7 more-login-options text-left">
          <%= link_to "more sign up options", '#' %>
        </div>

        <div class="col-md-5 text-right sign-up-button">
          <%= submit_tag "Sign up", class: "login-register-button white", id: "confirm-sign-up" %>
        </div>

        <div class="row">
          <div class="col-md-12 text-center">
            <p class="policy">By registering, you agree to the <span class="registration-policy">privacy policy</span> and <span class="registration-policy">terms of service.</span></p>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/_nav.html.erb
<div class="row">
  <ul class="nav nav-tabs">
    <li rol="presentation"><%= link_to "Log in", login_path, class: "link" %></li>
    <li rol="presentation" class="active"><%= link_to "Sign up", register_path, class: "link" %></li>
  </ul>
</div>

app/views/users/_registration_sub_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="registration-sub-div text-center">
      <p>Already have an account? <%= link_to "Log in", login_path %></p>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row static-width text-center main-content-container">
  <div class="col-md-10 col-md-offset-1">

    <%= render 'nav' %>

    <%= render partial: 'layouts/errors', locals: {element: @user} %>

    <%= render 'form' %>

    <%= render 'registration_sub_form' %>

  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>
<div>Member since <%= user_profile_date(@user.created_at) %></div>

<h3>Questions Asked</h3>
<ul>
  <% @user.questions.each do |qs| %>
    <li><%= link_to qs.title, question_path %></li>
  <% end %>
</ul>