config/routes.rb
Rails.application.routes.draw do
  root 'questions#newest'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'register' => 'users#new'
  resources :users, only: [:create, :show, :destroy]

  resources :questions, shallow: true do
    resources :answers, except: [:show, :index]
    resources :comments, except: [:index, :show]
  end
  get 'newest' => 'questions#newest', as: 'questions/newest'
  get 'trending' => 'questions#trending', as: 'questions/trending'
  get 'highest_voted' => 'questions#highest_voted', as: 'questions/highest_voted'

end

app/views/layouts/_errors.html.erb
<% if element.errors.any? %>
  <div class="row">
    <div class="errors col-md-4 col-md-offset-4">
      <ul class="no-list-style">
        <% element.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row main-footer">
  <div class="static-width">

    <div class="col-md-10 col-md-offset-1 first-footer">
      <%= render 'layouts/footer_sections/main' %>
    </div>

    <div class="col-md-10 col-md-offset-1 second-footer no-padding">

      <div class="col-md-5 no-padding">

        <div class="col-md-12">
          <%= render 'layouts/footer_sections/technology' %>
        </div>

      </div>

      <div class="col-md-7 no-padding">

        <div class="col-md-3">
          <%= render 'layouts/footer_sections/life_arts' %>
        </div>

        <div class="col-md-3">
          <%= render 'layouts/footer_sections/culture_recreation' %>
        </div>

        <div class="col-md-3">
          <%= render 'layouts/footer_sections/science' %>
        </div>

        <div class="col-md-3">
          <%= render 'layouts/footer_sections/other' %>
        </div>

      </div>

    </div>

    <div class="col-md-10 col-md-offset-1 third-footer">
      <p>site design / logo © 2016 Smack Undertone Inc; user contributions licensed under <span class="copright">cc by-sa 3.0</span> with <span class="copyright">attribution required</span></p>
      <p>rev 2016.1.1.3143</p>
    </div>


  </div>
</div>

app/views/layouts/_main_navbar.html.erb
<ul class="no-list-style main-navbar-link-container">
  <% if logged_in? %>
    <li class="inline primary-gray">
      Welcome, <%= current_user.username %>!
    </li>
    <li class="inline main-navbar-link">
      <%= link_to 'Logout', logout_path, method: 'delete' %>
    </li>
  <% else %>
    <li class="inline main-navbar-link">
      <%= link_to "sign up", register_path, class: "link primary-gray", id: "sign-up" %>
    </li>
    <li class="inline main-navbar-link">
      <%= link_to "log in", login_path, class: "link primary-gray" %>
    </li>
  <% end %>
  <li class="inline main-navbar-link">
    <%= link_to "tour", root_path, class: "link primary-gray" %>
  </li>
  <li class="inline main-navbar-link">
    <%= link_to "help", root_path, class: "link primary-gray" %>
  </li>
  <li class="inline main-navbar-link">
    <input placeholder="search" />
  </li>
</ul>

app/views/layouts/_secondary_navbar.html.erb
<ul class="no-list-style secondary-navbar-link-container">
  <li class="inline secondary-navbar-link"><%= link_to "Questions", questions_path, class: "link white" %></li>
  <li class="inline secondary-navbar-link"><%= link_to "Jobs", root_path, class: "link white" %></li>
  <li class="inline secondary-navbar-link"><%= link_to "Tags", root_path, class: "link white" %></li>
  <li class="inline secondary-navbar-link"><%= link_to "Users", root_path, class: "link white" %></li>
  <li class="inline secondary-navbar-link"><%= link_to "Badges", root_path, class: "link white" %></li>
  <li class="inline secondary-navbar-link"><%= link_to "Ask Question", new_question_path, class: "link white" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmackUndertone</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="row main-navbar">
      <div class="static-width">

        <div class="col-md-3 col-md-offset-1">
          <%= link_to (image_tag "exchange-logo.png", class: "exchange-logo"), root_path, class: "link secondary-navbar-logo" %>
        </div>

        <div class="col-md-7 text-right main-navbar">
          <nav>
            <%= render 'layouts/main_navbar' %>
          </nav>
        </div>

      </div>
    </div>

    <div class="row secondary-navbar">
      <div class="static-width">

        <div class=" col-md-5 col-md-offset-1">
          <div class="col-md-6">
            <%= link_to (image_tag "smack-undertone-logo.png", class: "logo"), root_path, class: "link secondary-navbar-logo" %>
          </div>
        </div>

        <div class="col-md-5 text-right">
          <nav>
            <%= render 'layouts/secondary_navbar' %>
          </nav>
        </div>

      </div>
    </div>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>